import { useCallback, useEffect, useRef, useState } from 'react'
import {
  rounds,
  endings,
  nextRoundId,
  resolveEnding,
  flagEpilogues,
  initialCanvas,
  type CanvasState,
  type ChatMsg,
  type Option,
  type Speaker,
} from './game/script'

type Phase = 'intro' | 'playing' | 'ending'

const MSG_DELAY = 800 // 消息逐条弹出间隔（初玩者节奏）
const TAKEOVER_MS = 2400 // AI 全屏吞噬时长

const speakerMeta: Record<Speaker, { name: string; bubble: string; align: string; avatar: string }> = {
  client: { name: '客户 · 李总', bubble: 'bg-sky-900/70 border-sky-700/60', align: 'justify-start', avatar: '甲' },
  director: { name: '总监 · 阿May（私聊）', bubble: 'bg-violet-900/60 border-violet-700/50', align: 'justify-start', avatar: '监' },
  system: { name: '系统', bubble: 'bg-zinc-800/80 border-zinc-600/50 text-zinc-300 italic', align: 'justify-center', avatar: '' },
  me: { name: '你', bubble: 'bg-emerald-900/50 border-emerald-700/50', align: 'justify-end', avatar: '我' },
}

function Avatar({ s }: { s: Speaker }) {
  if (s === 'system') return null
  return (
    <div className="w-8 h-8 shrink-0 rounded-full bg-zinc-700 border border-zinc-500 flex items-center justify-center text-xs font-bold text-zinc-200">
      {speakerMeta[s].avatar}
    </div>
  )
}

function ChatBubble({ msg }: { msg: ChatMsg }) {
  const meta = speakerMeta[msg.from]
  if (msg.from === 'system') {
    return (
      <div className="flex justify-center animate-[fadeIn_.4s_ease]">
        <div className={`max-w-[95%] rounded-lg border px-3 py-2 text-xs leading-relaxed ${meta.bubble}`}>{msg.text}</div>
      </div>
    )
  }
  return (
    <div className={`flex gap-2 ${meta.align} animate-[fadeIn_.4s_ease]`}>
      {msg.from !== 'me' && <Avatar s={msg.from} />}
      <div className={`max-w-[85%] rounded-xl border px-3 py-2 text-sm leading-relaxed text-zinc-100 ${meta.bubble}`}>
        <div className="text-[10px] opacity-60 mb-0.5">{meta.name}</div>
        {msg.text}
      </div>
      {msg.from === 'me' && <Avatar s={msg.from} />}
    </div>
  )
}

/** 中间画布：一张海报，Logo 会长大 */
function Poster({ c }: { c: CanvasState }) {
  return (
    <div className="relative w-full max-w-[200px] md:max-w-none aspect-[3/4] max-h-full rounded-lg overflow-hidden border border-zinc-600 bg-gradient-to-b from-orange-100 to-amber-50 shadow-2xl">
      {/* 产品图（被 Logo 挡住时仍然渲染在底层） */}
      {!c.aiVersion && (
        <div className="absolute left-1/2 top-[62%] -translate-x-1/2 -translate-y-1/2 w-[26%] h-[34%]">
          <div className="w-full h-full rounded-t-3xl rounded-b-lg bg-gradient-to-b from-teal-500 to-teal-700 shadow-lg relative">
            <div className="absolute left-1/2 -translate-x-1/2 -top-[12%] w-[40%] h-[14%] rounded bg-teal-800" />
            <div className="absolute inset-x-2 top-[30%] h-[30%] rounded bg-white/85 flex items-center justify-center">
              <span className="text-[0.55rem] font-bold text-teal-800 tracking-widest">PRODUCT</span>
            </div>
          </div>
        </div>
      )}

      {/* Logo：核心笑点，带过渡动画地长大 */}
      <div
        className="absolute left-1/2 top-[6%] -translate-x-1/2 bg-zinc-800 rounded-sm shadow-xl flex items-center justify-center transition-all duration-700 ease-in-out z-10"
        style={{ width: `${c.logoSize}%`, aspectRatio: '1/1' }}
      >
        <span
          className="font-black text-zinc-100 tracking-tight transition-all duration-700"
          style={{ fontSize: `clamp(10px, ${c.logoSize * 0.28}px, 64px)` }}
        >
          LOGO
        </span>
        {c.productInLogo && (
          <div className="absolute right-[4%] bottom-[4%] w-[10%] h-[14%] rounded-t-md rounded-b-sm bg-teal-600" />
        )}
      </div>

      {c.slogan && (
        <div className="absolute bottom-[5%] inset-x-0 text-center z-20">
          <span className="text-lg font-black bg-gradient-to-r from-yellow-300 via-amber-500 to-yellow-300 bg-clip-text text-transparent animate-pulse drop-shadow-[0_0_6px_rgba(250,204,21,.8)]">
            ✦ 行业领导者 ✦
          </span>
        </div>
      )}

      {c.aiVersion && (
        <div className="absolute bottom-2 right-2 z-20 text-[10px] font-mono bg-black/70 text-green-400 px-2 py-1 rounded">
          GENERATED BY 智稿AI · 5min
        </div>
      )}
      {c.proVersion && !c.aiVersion && (
        <div className="absolute bottom-2 right-2 z-20 text-[10px] font-mono bg-black/70 text-zinc-300 px-2 py-1 rounded">
          v_专业版.psd
        </div>
      )}
    </div>
  )
}

export default function App() {
  const [phase, setPhase] = useState<Phase>('intro')
  const [roundId, setRoundId] = useState('r1')
  const [chat, setChat] = useState<ChatMsg[]>([])
  const [canvas, setCanvas] = useState<CanvasState>(initialCanvas)
  const [flags, setFlags] = useState<Record<string, boolean>>({})
  const [available, setAvailable] = useState<Option[]>([])
  const [busy, setBusy] = useState(false)
  const [canNext, setCanNext] = useState(false)
  const [endingId, setEndingId] = useState<string | null>(null)
  const [takeover, setTakeover] = useState(false) // AI 全屏吞噬
  const timers = useRef<ReturnType<typeof setTimeout>[]>([])
  const pending = useRef<{ msgs: ChatMsg[]; fired: number; done: () => void } | null>(null)
  const chatBox = useRef<HTMLDivElement>(null)
  const optionsBox = useRef<HTMLElement>(null)
  const lastChosenRef = useRef('')

  const clearTimers = () => {
    timers.current.forEach(clearTimeout)
    timers.current = []
  }

  useEffect(() => {
    chatBox.current?.scrollTo({ top: chatBox.current.scrollHeight, behavior: 'smooth' })
  }, [chat])

  // 手机端：选项出现时自动滚到选项区，避免玩家不知道还有选项
  useEffect(() => {
    if ((available.length > 0 || canNext) && !busy && window.matchMedia('(max-width: 767px)').matches) {
      const t = setTimeout(() => optionsBox.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 120)
      return () => clearTimeout(t)
    }
  }, [available.length, canNext, busy])

  useEffect(() => clearTimers, [])

  /** 逐条把消息推进聊天框；点聊天区可快进 */
  const pushMessages = useCallback((msgs: ChatMsg[], done: () => void) => {
    if (msgs.length === 0) {
      done()
      return
    }
    const p = { msgs, fired: 0, done }
    pending.current = p
    msgs.forEach((m, i) => {
      timers.current.push(
        setTimeout(() => {
          p.fired = i + 1
          setChat((prev) => [...prev, m])
          if (i === msgs.length - 1) {
            if (pending.current === p) pending.current = null
            done()
          }
        }, MSG_DELAY * (i + 1)),
      )
    })
  }, [])

  /** 快进：立即补完当前队列 */
  const flush = useCallback(() => {
    const p = pending.current
    if (!p) return
    clearTimers()
    pending.current = null
    const rest = p.msgs.slice(p.fired)
    if (rest.length) setChat((prev) => [...prev, ...rest])
    p.done()
  }, [])

  const startRound = useCallback(
    (id: string) => {
      const r = rounds[id]
      setRoundId(id)
      setAvailable(r.options)
      setCanNext(false)
      setBusy(true)
      if (r.canvas) setCanvas((c) => ({ ...c, ...r.canvas }))
      pushMessages(r.intro, () => setBusy(false))
    },
    [pushMessages],
  )

  const startGame = () => {
    clearTimers()
    pending.current = null
    setChat([])
    setFlags({})
    setCanvas(initialCanvas)
    setEndingId(null)
    setTakeover(false)
    lastChosenRef.current = ''
    setPhase('playing')
    startRound('r1')
  }

  const choose = (opt: Option) => {
    if (busy) return
    setBusy(true)
    const mergedFlags = opt.flags ? { ...flags, ...opt.flags } : flags
    if (opt.canvas) setCanvas((c) => ({ ...c, ...opt.canvas }))
    if (opt.flags) setFlags(mergedFlags)

    const afterReactions = () => {
      if (opt.ending) {
        setEndingId(resolveEnding(opt.ending, mergedFlags))
        setBusy(false)
        setCanNext(false)
        setPhase('ending')
        return
      }
      if (opt.funnel) {
        setAvailable((prev) => prev.filter((o) => o.id !== opt.id))
        setBusy(false)
      } else {
        setAvailable([])
        setBusy(false)
        setCanNext(true)
      }
    }

    if (opt.canvas?.aiVersion) {
      // AI 结局：Logo 先吃掉整个屏幕，再出反应
      setTakeover(true)
      timers.current.push(
        setTimeout(() => {
          setTakeover(false)
          pushMessages(opt.reactions, afterReactions)
        }, TAKEOVER_MS),
      )
    } else {
      pushMessages(opt.reactions, afterReactions)
    }
  }

  const chooseTracked = (opt: Option) => {
    if (!opt.funnel) lastChosenRef.current = opt.id
    choose(opt)
  }

  const goNext = () => {
    const next = nextRoundId(roundId, lastChosenRef.current)
    if (next) startRound(next)
  }

  const epilogues = flagEpilogues(flags)
  const ending = endingId ? endings[endingId] : null

  // ─────────────── 开场 ───────────────
  if (phase === 'intro') {
    return (
      <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col items-center justify-center gap-6 p-8">
        <div className="text-6xl font-black tracking-widest">再大一点</div>
        <div className="text-zinc-400 text-sm tracking-wide">一个你永远无法满足甲方需求的荒诞选择游戏</div>
        <div className="text-zinc-600 text-xs">DAY 1 · 三条需求 · 九个结局 · 大约 3 分钟</div>
        <button
          onClick={startGame}
          className="mt-4 px-10 py-4 rounded-xl bg-amber-500 hover:bg-amber-400 text-zinc-950 font-black text-lg tracking-widest transition-colors shadow-[0_0_30px_rgba(245,158,11,.35)]"
        >
          接单
        </button>
      </div>
    )
  }

  // ─────────────── 结局 ───────────────
  if (phase === 'ending' && ending) {
    return (
      <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col items-center justify-center gap-6 p-8">
        <div className="text-xs tracking-[0.5em] text-zinc-500">DAY 1 结束</div>
        <div className="text-4xl font-black text-center">{ending.title}</div>
        <div className="max-w-lg w-full space-y-3 mt-2">
          {ending.lines.map((m, i) => (
            <ChatBubble key={i} msg={m} />
          ))}
        </div>
        {epilogues.length > 0 && (
          <div className="max-w-lg w-full mt-4 rounded-xl border border-zinc-700 bg-zinc-900/60 p-4 space-y-1">
            <div className="text-xs text-zinc-500 mb-2">这一天留下的痕迹：</div>
            {epilogues.map((e, i) => (
              <div key={i} className="text-sm text-zinc-300">· {e}</div>
            ))}
          </div>
        )}
        <div className="text-zinc-600 text-sm mt-2">DAY 2（待续）</div>
        <button
          onClick={startGame}
          className="px-8 py-3 rounded-xl border border-amber-500/60 text-amber-400 hover:bg-amber-500/10 font-bold transition-colors"
        >
          再过一遍 DAY 1
        </button>
      </div>
    )
  }

  // ─────────────── 游戏主界面 ───────────────
  const round = rounds[roundId]
  return (
    <div className="h-screen bg-zinc-950 text-zinc-100 flex flex-col overflow-hidden">
      <header className="shrink-0 flex items-center justify-between px-5 py-3 border-b border-zinc-800">
        <div className="font-black tracking-widest">再大一点</div>
        <div className="text-xs text-zinc-500">DAY 1 · {round.label}</div>
      </header>

      <main className="flex-1 grid grid-cols-1 md:grid-cols-[1fr_1.1fr_1fr] gap-3 p-3 min-h-0 overflow-y-auto md:overflow-hidden">
        {/* 左：需求聊天（点按可快进） */}
        <section className="flex flex-col min-h-[40vh] md:min-h-0 rounded-xl border border-zinc-800 bg-zinc-900/40">
          <div className="shrink-0 px-4 py-2 border-b border-zinc-800 text-xs text-zinc-500 flex justify-between">
            <span>需求 / 私聊</span>
            {busy && <span className="text-zinc-600">点按可快进</span>}
          </div>
          <div ref={chatBox} onClick={flush} className="flex-1 overflow-y-auto p-3 space-y-3 cursor-pointer">
            {chat.map((m, i) => (
              <ChatBubble key={i} msg={m} />
            ))}
            {busy && <div className="text-center text-xs text-zinc-600 animate-pulse">……</div>}
          </div>
        </section>

        {/* 中：设计稿 */}
        <section className="flex flex-col min-h-0 rounded-xl border border-zinc-800 bg-zinc-900/40 p-3">
          <div className="shrink-0 text-xs text-zinc-500 pb-2 flex justify-between">
            <span>设计稿 · 海报.psd</span>
            <span className="font-mono">Logo 占比 {canvas.logoSize}%</span>
          </div>
          <div className="flex-1 min-h-0 flex items-center justify-center">
            <Poster c={canvas} />
          </div>
        </section>

        {/* 右：操作（手机端两列平铺，全部露出） */}
        <section ref={optionsBox} className="flex flex-col min-h-0 rounded-xl border border-zinc-800 bg-zinc-900/40">
          <div className="shrink-0 px-4 py-2 border-b border-zinc-800 text-xs text-zinc-500">你的操作</div>
          <div className="flex-1 overflow-y-auto p-3 grid grid-cols-2 md:grid-cols-1 gap-2 md:gap-3 content-start">
            {available.map((o) => (
              <button
                key={o.id}
                disabled={busy}
                onClick={() => chooseTracked(o)}
                className="w-full text-left rounded-xl border border-zinc-700 bg-zinc-800/60 hover:border-amber-500/70 hover:bg-amber-500/10 disabled:opacity-40 disabled:hover:border-zinc-700 disabled:hover:bg-zinc-800/60 p-3 md:p-4 transition-colors"
              >
                <div className="font-bold text-sm leading-snug">{o.label}</div>
                {o.sub && <div className="text-xs text-zinc-500 mt-1">{o.sub}</div>}
              </button>
            ))}
            {canNext && (
              <button
                onClick={goNext}
                className="col-span-2 md:col-span-1 w-full rounded-xl bg-amber-500 hover:bg-amber-400 text-zinc-950 font-black py-4 tracking-widest transition-colors"
              >
                下一条需求 →
              </button>
            )}
            {!canNext && available.length === 0 && busy && (
              <div className="col-span-2 md:col-span-1 text-center text-xs text-zinc-600 animate-pulse pt-4">等待对方回复……</div>
            )}
          </div>
        </section>
      </main>

      {/* AI 全屏吞噬：需求越过第四面墙，吃掉游戏本身 */}
      {takeover && (
        <div className="fixed inset-0 z-50 flex items-center justify-center overflow-hidden bg-zinc-950/40">
          <div className="bg-zinc-800 flex items-center justify-center animate-[takeoverZoom_1.1s_ease-in_forwards]">
            <span className="font-black text-zinc-100 tracking-tight animate-[takeoverText_1.1s_ease-in_forwards]">LOGO</span>
          </div>
        </div>
      )}
    </div>
  )
}
